### ISSUE TITLE
How to decrypt encrypted traffic

### ISSUE THREAD

**Issue by hegugu-ng** [Sorapointa/Sorapointa#112]
昨天，我查看了一下udp数据包，总结了一些规律，但是我不知道如何解密DATA。
我在试图找一些关于加密过程的资料，但是并没有找到，不知道您是否可以提供一些帮助。
C <-> S
00 00 00 00 00 00 00 00 AA 00 00 01 BB BB A5 C1
CC CC CC CC DD DD DD DD EE EE EE EE DATA
AA -> 51/52:C/S
BB -> OP?
CC -> SC 
DD -> RC 
EE -> LEN

Yesterday, I checked the udp packet and summarized some rules, but I don't know how to decrypt DATA.

I was trying to find some information about the encryption process, but I couldn't find it. I wonder if you could provide some help.

**Comment by WetABQ** [comment]
See https://sdl.moe/post/magic-sniffer/

**Comment by dfaofeng** [comment]
> 昨天，我查看了一下udp数据包，总结了一些规律，但是我不知道如何解密DATA。 我在试图找一些关于加密过程的资料，但是并没有找到，不知道您是否可以提供一些帮助。 C <-> S 00 00 00 00 00 00 00 00 AA 00 00 01 BB BB A5 C1 CC CC CC CC DD DD DD DD EE EE EE EE DATA AA -> 51/52:C/S BB -> OP? CC -> SC DD -> RC EE -> LEN
> 
> Yesterday, I checked the udp packet and summarized some rules, but I don't know how to decrypt DATA.
> 
> I was trying to find some information about the encryption process, but I couldn't find it. I wonder if you could provide some help.

你需要参考这里的代码 主要关于xor解密相关的
