### ISSUE TITLE
2.7 Could not join the game server

### ISSUE THREAD

**Issue by FENGXIpersion** [Sorapointa/Sorapointa#41]
![LFD}C$SR$P$MJC$GL8 QAEJ](https://user-images.githubusercontent.com/90132056/173223502-f73747fd-577e-406d-9139-d791fe2a9957.png)
是这个错误影响的吗？这个错误是什么？

----

Translated:

It seems like to be caused by this exception, what is that?

**Comment by Colerar** [comment]
和此问题有一定的关系。可能是系统权限（如防火墙设置）相关问题。可以切到 [updated-game-server 分支](https://github.com/Sorapointa/Sorapointa/tree/updated-game-server)看看是否解决。

然而正如 Sorapointa README 中写的：「WIP: 该项目正被积极开发，你可以参与贡献，但大多数功能不可用。」

现在的进度是 Dispatch 能登录。
