### ISSUE TITLE
Convert `lua` file to `.kt` or `.json`

### ISSUE THREAD

**Issue by Colerar** [Sorapointa/Sorapointa#44]
## Purpose

**Why do conversion instead of embedding a Lua interpreter?**

- The interoperability between kotlin/java and Lua is pretty bad.
  - [Rembulan](https://github.com/mjanicek/rembulan) cannot parse big `lua` file.
  - The JNI bindings (e.g. [JNLua](https://github.com/MovingBlocks/JNLua)) involve extra complexity, we must compile every platform and every architecture manually to ensure the cross-platform compatibility.
- We cannot get more Lua files of the *anime game* in the future. We must write code ourselves.

## How

For big data Lua files (without state), we can convert it to JSON easily:

```lua
-- Lua script to JSON demo
Json = require("json") -- https://github.com/rxi/json.lua

loadfile("./path/to/lua")()

local toEncode = varOfLuaScript

local output = io.open("output.json", "w")
if output ~= nil then
    output:write(Json.encode(toEncode))
end
```

For `lua` files with state, we can deobfuscate them first (reduce complexity), then convert them to `.kt` by a set of regex or the AST parser (e.g. [ANTLR](https://www.antlr.org/))

**Comment by WetABQ** [comment]
After the big leaking of the certain anime game, it released more Lua script files (without obf). We may not adopt this method.

**Comment by WetABQ** [comment]
See #59
