### ISSUE TITLE
Replace i18n implementation by resource bundles

### ISSUE THREAD

**Issue by Bartvhelvert** [Sorapointa/Sorapointa#50]
The JDK already provides this functionality in the form of [resource bundles](https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html).

We can store the messages in `.properties` files and use [PropertiesResourceBundle](https://docs.oracle.com/javase/7/docs/api/java/util/PropertyResourceBundle.html) to manage them. Then, using Jetbrains annotations like [`@PropertyKey`](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/PropertyKey.java) to get auto complete and other nice features in the editor. This should also work nicely with [`@Nls`](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/Nls.java) and [`@NonNls`](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/NonNls.java) annotations.

**Comment by Bartvhelvert** [comment]
I can try to implement something if you guys think it is a good idea.

**Comment by WetABQ** [comment]
> I can try to implement something if you guys think it is a good idea.

We will discuss it, but i don’t think we could response you today since we are in UTC+8:00, so… maybe tormorrow. Anyway, thanks for your good suggestion.

**Comment by Colerar** [comment]
Thanks for your suggestion. It's a good idea.

As you mentioned, the properties format is better. There are many tools (including IDEA) to help us do i18n.

What changed is only the format. So we could be able to switch to properties smoothly.
