### ISSUE TITLE
Switch protobuf backend to `wire`

### ISSUE THREAD

**Issue by Colerar** [Sorapointa/Sorapointa#56]
## Description

Compared with `protoc`, [Wire](https://github.com/square/wire) is more suitable for Kotlin, and has faster compilation speed, runtime performance, and smaller jar size.

## Advantages

- It can generate pure Kotlin code without any Java dependencies. The generated code is much cleaner than the protoc's result, like hand-written code.
- It is integrated with a well-known high-performance IO library, [Okio](https://github.com/square/okio), then we can read/write from/to asynchronous binary stream, which may have better runtime performance.
- Wire claims to be optimized for Android, so it generates much fewer lines of code than `protoc`.

**Comment by WetABQ** [comment]
dcb39ec2cd3a97b6d987a22046f20769910e034e
