### ISSUE TITLE
Refactor Sorapointa Network Module by WebSocket

### ISSUE THREAD

**Issue by WetABQ** [Sorapointa/Sorapointa#58]
## Description

- Replace the original KCP protocol with WebSocket. 
- Communicate with the client by `sorapointa-protocol-bridge`.

## Advantages

- KCP doesn't have an official or stable implementation for Kotlin, altering to WebSocket will be better for development and performance.
- Will not need to follow the proto change caused by "upstream".

## See Also

#57

**Comment by Colerar** [comment]
- Cross-language asynchronous is often undefined (e.g., calling Rust via JNI)
- Implementing KCP via WebSocket may introduce additional overhead
- Rust crate `tokio-kcp` implementation is difficult to modify and may be as difficult as rewriting KCP in Kotlin

All in all, after trying, we ended up opting to implement KCP in Kotlin.
